# Pin npm packages by running ./bin/importmap

pin "application", to: "main.js"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin "@rails/activestorage", to: "activestorage.esm.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "lessons_filter"
pin "controllers/subscribers_controller", to: "controllers/subscribers_controller.js"
pin "@uppy/core", to: "https://ga.jspm.io/npm:@uppy/core@3.12.0/lib/index.js"
pin "@uppy/aws-s3-multipart", to: "https://ga.jspm.io/npm:@uppy/aws-s3-multipart@3.6.0/lib/index.js"
pin "@uppy/utils", to: "https://ga.jspm.io/npm:@uppy/utils@5.9.0/lib/index.js"
pin "@uppy/store-default", to: "https://ga.jspm.io/npm:@uppy/store-default@3.2.2/lib/index.js"
pin "@uppy/companion-client", to: "https://ga.jspm.io/npm:@uppy/companion-client@3.8.1/lib/index.js"
pin "video_multipart_uploader", to: "video_multipart_uploader.js"
